org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
# This is now the default value as of AGP 9.0
android.useAndroidX=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
# This is now the default value
android.builtInKotlin=true

# These flags apply AGP 7.0 default settings
#android.nonTransitiveRClass=false
#android.nonFinalResIds=false

# These flags apply AGP 8.0 default settings
# From preliminary testing, only resValues seem to be needed
android.defaults.buildfeatures.resvalues=true
#android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
#android.enableAppCompileTimeRClass=false
#android.usesSdkInManifest.disallowed=false
#android.uniquePackageNames=false
#android.dependency.useConstraints=true
# Suspicious, default of true can apparently cause runtime crashes if not set up correctly.
#android.r8.strictFullModeForKeepRules=false
#android.r8.optimizedResourceShrinking=false

